### ISSUE TITLE
Duplicate?

### ISSUE THREAD

**Issue by stevenvachon** [wooorm/html-void-elements#5]
of [void-elements](https://npmjs.com/void-elements)

**Comment by wooorm** [comment]
They do similar things, yes, but this project’s API is different (array instead of object) and has more (legacy) elements.

**Comment by stevenvachon** [comment]
@wooorm A redundant package is necessary to have an Array (`O(n)`) instead of an Object (`O(1)`)? You could have created a pull request for the other package, adding the legacy elements.

**Comment by wooorm** [comment]
> A redundant package […]

As noted above, this package is not redundant, because there are differences.

> […] is necessary […]

[I don’t claim this package is necessary](https://github.com/wooorm/html-void-elements/blob/770d725ca6a615e366ed53fb591db76024a2e6fe/license#L16-L18).

> […] to have an Array (O(n)) instead of an Object (O(1))? […]

That is in my opinion a reason for something to exist, yes.

> […] You could have created a pull request for the other package […]

I could have done that. I sometimes do.
At the time the projects [were more different](https://github.com/pugjs/void-elements/commit/ab0e8f7f191f2ce55a7c2ccec451c1528b44a272).

> […] adding the legacy elements.
 
That project [actively removed deprecated elements](https://github.com/pugjs/void-elements/commit/0879db0a9a04df62880233f2f036013266d13611).

---

Stop picking a fight.

**Comment by stevenvachon** [comment]
Call it what you like, but redundant, unnecessary packages are an active problem on NPM. Please keep that in mind.
